### ISSUE TITLE
Conflicts with the Philomena's built-in autocomplete functionality

### ISSUE THREAD

**Issue by koloml** [usyless/Derpibooru-Tag-Autocomplete#2]
I think extension should either forcibly turn off the built-in autocomplete functionality, or notify the user about this conflict. Because right now you would need to manually do that, otherwise you would see this:

![image](https://github.com/user-attachments/assets/8b920295-91df-4fe5-9986-f1206642aac4)

As a hint, it could be done by removing these attributes from the field:

![image](https://github.com/user-attachments/assets/8b3de169-c2a1-474d-9836-415a3fc6e285)

Philomena looks for these properties on interaction and not on the page load, so autocomplete will just turn off without any issues.

**Comment by usyless** [comment]
Oh I hadn't considered doing that, thanks for the info, I will add it today. (I also notice the theme colour mismatch, I'll see if I can make it follow the selected theme)

**Comment by koloml** [comment]
Yeah, themes are not synced up and the only workarounds for that are either copy-pasting theme colors from the site or re-using the website classes.

Regarding the visual stuff, I also noticed this line under the input:

![image](https://github.com/user-attachments/assets/65922690-51ab-4377-bbb1-62a9e322c961)

You should probably hide everything by default.

**Comment by usyless** [comment]
Built in autocomplete showing while using this extension and theme colours fixed in [v1.2.1.3](https://github.com/usyless/Derpibooru-Tag-Autocomplete/releases/tag/v1.2.1.3)

It's now approved on firefox so if you force an extension update you should get it
