### ISSUE TITLE
Latest Derpibooru themes update makes plugin mismatch the theme again

### ISSUE THREAD

**Issue by koloml** [usyless/Derpibooru-Tag-Autocomplete#3]
This time you don't event need to copy all the colors for all 18 themes — they're introduced CSS variables for colors which you could simply reuse.

See https://derpibooru.org/forums/meta/topics/new-themes-and-stylesheets

![image](https://github.com/user-attachments/assets/675448c2-e806-4407-a7d7-7a15bcbae8e8)

**Comment by usyless** [comment]
Oh, awesome! Thanks for this info, I'll update the extension.

**Comment by usyless** [comment]
Updated, supports all themes now with version [v1.2.5](https://github.com/usyless/Derpibooru-Tag-Autocomplete/releases/tag/v1.2.5).

Also is approved and out on firefox.
